function EnableLucky()
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(None, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(Attack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeWeaponAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedWeaponAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeSpellAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedSpellAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeUnarmedAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedUnarmedAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(SkillCheck, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(SavingThrow, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RawAbility, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(Damage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeOffHandWeaponAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedOffHandWeaponAttack, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(DeathSavingThrow, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeWeaponDamage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedWeaponDamage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeSpellDamage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedSpellDamage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(MeleeUnarmedDamage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(RangedUnarmedDamage, 20)", "", GetHostCharacter())
    Osi.AddBoosts(GetHostCharacter(), "MinimumRollResult(Sentinel, 20)", "", GetHostCharacter())    
end

function DisableLucky()
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(None, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(Attack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeWeaponAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedWeaponAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeSpellAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedSpellAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeUnarmedAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedUnarmedAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(SkillCheck, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(SavingThrow, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RawAbility, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(Damage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeOffHandWeaponAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedOffHandWeaponAttack, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(DeathSavingThrow, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeWeaponDamage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedWeaponDamage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeSpellDamage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedSpellDamage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(MeleeUnarmedDamage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(RangedUnarmedDamage, 20)", 0, "", GetHostCharacter())
    Osi.RemoveBoosts(GetHostCharacter(), "MinimumRollResult(Sentinel, 20)", 0, "", GetHostCharacter())    
end


function RemoveScaleMultiplier()
    for _, boostEntry in ipairs(Ext.Entity.Get(GetHostCharacter()).BoostsContainer.Boosts) do
        if boostEntry.Type == "ScaleMultiplier" then
            for _, b in pairs(boostEntry.Boosts) do
                for _, z in pairs(b.ScaleMultiplierBoost) do
                    Osi.RemoveBoosts(GetHostCharacter(), "ScaleMultiplier(" .. z .. ")", 0, "", GetHostCharacter())
                end
            end
        end
    end
end


function UnlockWaypoints()
    Osi.PROC_UnlockWaypoint("WAYP_HAG_Swamp", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_DEN_Camp", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_CHA_Chapel", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_CHA_Top", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_PLA_Toll", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_GOB_Temple", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_PLA_Tavern", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_FOR_Ruins", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_FOR_Bottomless", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_PLA_ZhentDungeon", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_Beach", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_Duergar", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_Sussur", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_Myconid", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_Fort", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_GP_HookHorror", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_UND_AdamantineForge", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_CRE_Exterior", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_CRE_Creche", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_CRE_Monastery", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_HAV_Outside", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_MOO_TowerExterior", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_SHA_NightsongPrison_Entrance", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_TWN_Center", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_TWN_Mausoleum", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_SHA_Temple", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_SCL_Highroad", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_SCL_OliverHouse", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_WYR_Rivington", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_WYR_SharessCaress", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_WYR_WyrmRock", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_CazadorsPalace", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_StartingArea", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_CentralWall", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_BaldursGateArea", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_DocksArea", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_CityBeach", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_Cesspool", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_UndercityRuins", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_BhaalTemple", GetHostCharacter())
    Osi.PROC_UnlockWaypoint("WAYP_LOW_MorphicPoolDoc", GetHostCharacter())        
end


function LockWaypoints()
    Osi.PROC_LockWaypoint("WAYP_HAG_Swamp", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_DEN_Camp", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_CHA_Chapel", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_CHA_Top", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_PLA_Toll", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_GOB_Temple", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_PLA_Tavern", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_FOR_Ruins", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_FOR_Bottomless", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_PLA_ZhentDungeon", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_Beach", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_Duergar", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_Sussur", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_Myconid", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_Fort", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_GP_HookHorror", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_UND_AdamantineForge", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_CRE_Exterior", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_CRE_Creche", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_CRE_Monastery", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_HAV_Outside", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_MOO_TowerExterior", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_SHA_NightsongPrison_Entrance", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_TWN_Center", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_TWN_Mausoleum", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_SHA_Temple", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_SCL_Highroad", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_SCL_OliverHouse", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_WYR_Rivington", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_WYR_SharessCaress", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_WYR_WyrmRock", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_CazadorsPalace", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_StartingArea", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_CentralWall", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_BaldursGateArea", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_DocksArea", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_CityBeach", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_Cesspool", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_UndercityRuins", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_BhaalTemple", GetHostCharacter())
    Osi.PROC_LockWaypoint("WAYP_LOW_MorphicPoolDoc", GetHostCharacter())
end